/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelapp;

import javax.swing.ImageIcon;

/**
 *
 * @author robert
 */
public class RoomGUI extends javax.swing.JFrame {

    /**
     * Creates new form SearchGUI
     */
    public RoomGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        manageRoomBtn = new javax.swing.JLabel();
        splitter1 = new javax.swing.JLabel();
        bookingsBtn = new javax.swing.JLabel();
        splitter2 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mngRoomHeader_Lbl = new javax.swing.JLabel();
        roomType_Lbl = new javax.swing.JLabel();
        roomType_Combo = new javax.swing.JComboBox<>();
        roomID_Tf = new javax.swing.JTextField();
        roomID_Lbl = new javax.swing.JLabel();
        address_Lbl = new javax.swing.JLabel();
        address_Tf = new javax.swing.JTextField();
        city_Lbl = new javax.swing.JLabel();
        city_Tf = new javax.swing.JTextField();
        price_Lbl = new javax.swing.JLabel();
        price_Tf = new javax.swing.JTextField();
        maxGuests_Lbl = new javax.swing.JLabel();
        maxGuests_Tf = new javax.swing.JTextField();
        breakfast_Lbl = new javax.swing.JLabel();
        breakfast_Check = new javax.swing.JCheckBox();
        parking_Lbl = new javax.swing.JLabel();
        parking_Check = new javax.swing.JCheckBox();
        kmCityCentre_Lbl = new javax.swing.JLabel();
        kmCityCentre_Tf = new javax.swing.JTextField();
        facilitiesHeader_Lbl = new javax.swing.JLabel();
        euroSymbol_Lbl = new javax.swing.JLabel();
        facility1_Check = new javax.swing.JCheckBox();
        facility4_Check = new javax.swing.JCheckBox();
        facility3_Check = new javax.swing.JCheckBox();
        facility2_Check = new javax.swing.JCheckBox();
        facility5_Check = new javax.swing.JCheckBox();
        facility8_Check = new javax.swing.JCheckBox();
        facility7_Check = new javax.swing.JCheckBox();
        facility6_Check = new javax.swing.JCheckBox();
        facilityOption_Lbl = new javax.swing.JLabel();
        facilityOption1_Rb = new javax.swing.JRadioButton();
        facilityOption2_Rb = new javax.swing.JRadioButton();
        facilityOption3_Rb = new javax.swing.JRadioButton();
        add_Btn = new javax.swing.JButton();
        clear_Btn = new javax.swing.JButton();
        viewAll_Btn = new javax.swing.JButton();
        viewHotel_Btn = new javax.swing.JButton();
        viewHostel_Btn = new javax.swing.JButton();
        viewBB_Btn = new javax.swing.JButton();
        delete_Btn = new javax.swing.JButton();
        removeHeader_Lbl = new javax.swing.JLabel();
        deleteID_Lbl = new javax.swing.JLabel();
        deleteID_Tf = new javax.swing.JTextField();
        createHeader_Lbl = new javax.swing.JLabel();
        save_Btn = new javax.swing.JButton();
        deleteRoomType_Combo = new javax.swing.JComboBox<>();
        catalogueHeader_Lbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1100, 750));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 204));
        backgroundPanel.setMaximumSize(new java.awt.Dimension(50, 50));

        headerPanel.setBackground(new java.awt.Color(153, 0, 51));
        headerPanel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        manageRoomBtn.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        manageRoomBtn.setForeground(new java.awt.Color(250, 250, 250));
        manageRoomBtn.setText("Manage Room");
        manageRoomBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        splitter1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        splitter1.setForeground(new java.awt.Color(255, 255, 204));
        splitter1.setText("|");

        bookingsBtn.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        bookingsBtn.setForeground(new java.awt.Color(255, 255, 204));
        bookingsBtn.setText("Bookings");
        bookingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsBtnMouseClicked(evt);
            }
        });

        splitter2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        splitter2.setForeground(new java.awt.Color(255, 255, 204));
        splitter2.setText("|");

        searchBtn.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 204));
        searchBtn.setText("Search");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Look, book, manage");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(splitter2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitter1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageRoomBtn)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageRoomBtn)
                    .addComponent(splitter1)
                    .addComponent(bookingsBtn)
                    .addComponent(splitter2)
                    .addComponent(searchBtn))
                .addContainerGap())
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mngRoomHeader_Lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mngRoomHeader_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mngRoomHeader_Lbl.setText("Manage Rooms");
        mngRoomHeader_Lbl.setToolTipText("");
        mngRoomHeader_Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));

        roomType_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomType_Lbl.setText("Room Type:");

        roomType_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Room", "Hostel Room", "Bed & Breakfast" }));
        roomType_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomType_ComboActionPerformed(evt);
            }
        });

        roomID_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomID_TfActionPerformed(evt);
            }
        });

        roomID_Lbl.setText("ID:");

        address_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        address_Lbl.setText("Address:");

        city_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        city_Lbl.setText("City:");

        price_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        price_Lbl.setText("Price per Night:");

        maxGuests_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maxGuests_Lbl.setText("Maximum Guests:");

        breakfast_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        breakfast_Lbl.setText("Breakfast Included:");

        breakfast_Check.setBackground(new java.awt.Color(255, 255, 204));

        parking_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        parking_Lbl.setText("Parking Space Available:");

        parking_Check.setBackground(new java.awt.Color(255, 255, 204));
        parking_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parking_CheckActionPerformed(evt);
            }
        });

        kmCityCentre_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kmCityCentre_Lbl.setText("Km from City Centre:");

        kmCityCentre_Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmCityCentre_TfActionPerformed(evt);
            }
        });

        facilitiesHeader_Lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        facilitiesHeader_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facilitiesHeader_Lbl.setText("Options - Hotel");

        euroSymbol_Lbl.setText("€");

        facility1_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility1_Check.setText("24/7 Reception");
        facility1_Check.setMaximumSize(new java.awt.Dimension(50, 50));
        facility1_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facility1_CheckActionPerformed(evt);
            }
        });

        facility4_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility4_Check.setText("Minibar");
        facility4_Check.setMaximumSize(new java.awt.Dimension(50, 50));

        facility3_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility3_Check.setText("Balcony");
        facility3_Check.setMaximumSize(new java.awt.Dimension(50, 50));

        facility2_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility2_Check.setText("Room Service");
        facility2_Check.setMaximumSize(new java.awt.Dimension(50, 50));

        facility5_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility5_Check.setText("Bathtub");
        facility5_Check.setMaximumSize(new java.awt.Dimension(50, 50));
        facility5_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facility5_CheckActionPerformed(evt);
            }
        });

        facility8_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility8_Check.setText("Gym");
        facility8_Check.setMaximumSize(new java.awt.Dimension(50, 50));

        facility7_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility7_Check.setText("Swimming Pool");
        facility7_Check.setMaximumSize(new java.awt.Dimension(50, 50));
        facility7_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facility7_CheckActionPerformed(evt);
            }
        });

        facility6_Check.setBackground(new java.awt.Color(255, 255, 204));
        facility6_Check.setText("Restaurant");
        facility6_Check.setMaximumSize(new java.awt.Dimension(50, 50));

        facilityOption_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        facilityOption_Lbl.setText("Bed Type:");

        facilityOption1_Rb.setBackground(new java.awt.Color(255, 255, 204));
        facilityOption1_Rb.setText("Simple");

        facilityOption2_Rb.setBackground(new java.awt.Color(255, 255, 204));
        facilityOption2_Rb.setText("Double");

        facilityOption3_Rb.setBackground(new java.awt.Color(255, 255, 204));
        facilityOption3_Rb.setText("King Size");

        add_Btn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add_Btn.setText("Add Room");

        clear_Btn.setText("Clear Form");

        viewAll_Btn.setText("View All");

        viewHotel_Btn.setText("Hotel Rooms");

        viewHostel_Btn.setText("Hostel Rooms");

        viewBB_Btn.setText("Bed & Breakfasts");
        viewBB_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBB_BtnActionPerformed(evt);
            }
        });

        delete_Btn.setText("Delete");

        removeHeader_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeHeader_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeHeader_Lbl.setText("Delete Room");
        removeHeader_Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51)));

        deleteID_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deleteID_Lbl.setText("Enter Room ID:");

        createHeader_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createHeader_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createHeader_Lbl.setText("Create New Room");
        createHeader_Lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true));

        save_Btn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save_Btn.setText("Save All");
        save_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_BtnActionPerformed(evt);
            }
        });

        deleteRoomType_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Room", "Hostel Room", "Bed & Breakfast" }));
        deleteRoomType_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomType_ComboActionPerformed(evt);
            }
        });

        catalogueHeader_Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        catalogueHeader_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catalogueHeader_Lbl.setText("Catalogue");
        catalogueHeader_Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51)));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));

        jSeparator2.setForeground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mngRoomHeader_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createHeader_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(facilitiesHeader_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(address_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(city_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roomType_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addComponent(roomType_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(roomID_Lbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(roomID_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(address_Tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(city_Tf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(price_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(price_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(euroSymbol_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(maxGuests_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(breakfast_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(parking_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(maxGuests_Tf, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(breakfast_Check, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(parking_Check)))
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(kmCityCentre_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kmCityCentre_Tf))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundPanelLayout.createSequentialGroup()
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addComponent(facilityOption_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(facilityOption1_Rb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(facility2_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(facility1_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(removeHeader_Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(facility4_Check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addComponent(facility3_Check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                                .addComponent(deleteID_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(deleteID_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(facilityOption2_Rb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(facility5_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(facility6_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteRoomType_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(facility8_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(facility7_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(facilityOption3_Rb, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(delete_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewBB_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(viewHostel_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewHotel_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewAll_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(save_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(catalogueHeader_Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(70, 70, 70))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(mngRoomHeader_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createHeader_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catalogueHeader_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(viewAll_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(viewHotel_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(viewHostel_Btn)
                                .addGap(18, 18, 18)
                                .addComponent(viewBB_Btn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roomType_Lbl)
                                    .addComponent(roomID_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomType_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomID_Lbl)
                                    .addComponent(maxGuests_Lbl)
                                    .addComponent(maxGuests_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(address_Lbl)
                                    .addComponent(address_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(breakfast_Lbl)
                                    .addComponent(breakfast_Check))
                                .addGap(22, 22, 22)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(city_Lbl)
                                    .addComponent(city_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(parking_Lbl)
                                    .addComponent(parking_Check))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(price_Lbl)
                                        .addComponent(price_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(euroSymbol_Lbl))
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(kmCityCentre_Lbl)
                                        .addComponent(kmCityCentre_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facilitiesHeader_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facilityOption1_Rb)
                    .addComponent(facilityOption2_Rb)
                    .addComponent(facilityOption3_Rb)
                    .addComponent(facilityOption_Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(facility1_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facility2_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(facility3_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility5_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility7_Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear_Btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(facility4_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility6_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facility8_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_Btn))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_Btn)
                    .addComponent(delete_Btn)
                    .addComponent(deleteID_Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteID_Lbl)
                    .addComponent(removeHeader_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteRoomType_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteRoomType_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomType_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRoomType_ComboActionPerformed

    private void save_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_BtnActionPerformed

    private void viewBB_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBB_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBB_BtnActionPerformed

    private void facility7_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facility7_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facility7_CheckActionPerformed

    private void facility5_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facility5_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facility5_CheckActionPerformed

    private void facility1_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facility1_CheckActionPerformed

    }//GEN-LAST:event_facility1_CheckActionPerformed

    private void kmCityCentre_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmCityCentre_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmCityCentre_TfActionPerformed

    private void parking_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parking_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parking_CheckActionPerformed

    private void roomID_TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomID_TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomID_TfActionPerformed

    private void roomType_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomType_ComboActionPerformed
        if (roomType_Combo.getSelectedItem().equals("Hotel Room")) {
            facilitiesHeader_Lbl.setText("Options - Hotel");
            facility1_Check.setText("24/7 Reception");
            facility2_Check.setText("Room Service");
            facility3_Check.setText("Balcony");
            facility4_Check.setText("Minibar");
            facility5_Check.setText("Bathtub");
            facility6_Check.setText("Restaurant");
            facility7_Check.setText("Swimming pool");
            facility8_Check.setText("Gym");
            facilityOption_Lbl.setText("Bed Type:");
            facilityOption1_Rb.setText("Simple");
            facilityOption2_Rb.setText("Double");
            facilityOption3_Rb.setText("King Size");
        } else if (roomType_Combo.getSelectedItem().equals("Hostel Room")){
            facilitiesHeader_Lbl.setText("Options - Hostel");
            facility1_Check.setText("24/7 Reception");
            facility2_Check.setText("Private Rooms");
            facility3_Check.setText("Lockers");
            facility4_Check.setText("Bar");
            facility5_Check.setText("Private Bathroom");
            facility6_Check.setText("Shared Kitchen");
            facility7_Check.setText("Washing Machine");
            facility8_Check.setText("Long Stay Option");
            facilityOption_Lbl.setText("Dormitory Type:");
            facilityOption1_Rb.setText("Female");
            facilityOption2_Rb.setText("Male");
            facilityOption3_Rb.setText("Mixed");
        } else {
            facilitiesHeader_Lbl.setText("Options - Bed & Breakfast");
            facility1_Check.setText("Owner Occupied");
            facility2_Check.setText("Pet Friendly");
            facility3_Check.setText("Kitchen Area");
            facility4_Check.setText("Cleaning Option");
            facility5_Check.setText("Towels Provided");
            facility6_Check.setText("Linen Provided");
            facility7_Check.setText("Washing Machine");
            facility8_Check.setText("Linen Provided");
            facilityOption_Lbl.setText("Bedrooms:");
            facilityOption1_Rb.setText("1");
            facilityOption2_Rb.setText("2");
            facilityOption3_Rb.setText("3");
        }
    }//GEN-LAST:event_roomType_ComboActionPerformed

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked

        SearchGUI s = new SearchGUI();

        // Get the size of the active window
        int sizeH = this.getSize().height;
        int sizeW = this.getSize().width;

        // Get the location of the active window
        int currX = this.getLocation().x;
        int currY = this.getLocation().y;

        // Set the size of the new window
        s.setSize(sizeW, sizeH);

        // Set the location of the new window
        s.setLocation(currX, currY);

        // Hide the active window, show the new window
        this.dispose();

        // Set the window icon
        ImageIcon img = new ImageIcon("img/logo.png");
        s.setIconImage(img.getImage());

        s.setVisible(true);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void bookingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsBtnMouseClicked

        BookingsGUI b = new BookingsGUI();

        // Get the size of the active window
        int sizeH = this.getSize().height;
        int sizeW = this.getSize().width;

        // Get the location of the active window
        int currX = this.getLocation().x;
        int currY = this.getLocation().y;

        // Set the size of the new window
        b.setSize(sizeW, sizeH);

        // Set the location of the new window
        b.setLocation(currX, currY);

        // Hide the active window, show the new window
        this.dispose();

        // Set the window icon
        ImageIcon img = new ImageIcon("img/logo.png");
        b.setIconImage(img.getImage());

        b.setVisible(true);
    }//GEN-LAST:event_bookingsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Btn;
    private javax.swing.JLabel address_Lbl;
    private javax.swing.JTextField address_Tf;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel bookingsBtn;
    private javax.swing.JCheckBox breakfast_Check;
    private javax.swing.JLabel breakfast_Lbl;
    private javax.swing.JLabel catalogueHeader_Lbl;
    private javax.swing.JLabel city_Lbl;
    private javax.swing.JTextField city_Tf;
    private javax.swing.JButton clear_Btn;
    private javax.swing.JLabel createHeader_Lbl;
    private javax.swing.JLabel deleteID_Lbl;
    private javax.swing.JTextField deleteID_Tf;
    private javax.swing.JComboBox<String> deleteRoomType_Combo;
    private javax.swing.JButton delete_Btn;
    private javax.swing.JLabel euroSymbol_Lbl;
    private javax.swing.JLabel facilitiesHeader_Lbl;
    private javax.swing.JCheckBox facility1_Check;
    private javax.swing.JCheckBox facility2_Check;
    private javax.swing.JCheckBox facility3_Check;
    private javax.swing.JCheckBox facility4_Check;
    private javax.swing.JCheckBox facility5_Check;
    private javax.swing.JCheckBox facility6_Check;
    private javax.swing.JCheckBox facility7_Check;
    private javax.swing.JCheckBox facility8_Check;
    private javax.swing.JRadioButton facilityOption1_Rb;
    private javax.swing.JRadioButton facilityOption2_Rb;
    private javax.swing.JRadioButton facilityOption3_Rb;
    private javax.swing.JLabel facilityOption_Lbl;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kmCityCentre_Lbl;
    private javax.swing.JTextField kmCityCentre_Tf;
    private javax.swing.JLabel manageRoomBtn;
    private javax.swing.JLabel maxGuests_Lbl;
    private javax.swing.JTextField maxGuests_Tf;
    private javax.swing.JLabel mngRoomHeader_Lbl;
    private javax.swing.JCheckBox parking_Check;
    private javax.swing.JLabel parking_Lbl;
    private javax.swing.JLabel price_Lbl;
    private javax.swing.JTextField price_Tf;
    private javax.swing.JLabel removeHeader_Lbl;
    private javax.swing.JLabel roomID_Lbl;
    private javax.swing.JTextField roomID_Tf;
    private javax.swing.JComboBox<String> roomType_Combo;
    private javax.swing.JLabel roomType_Lbl;
    private javax.swing.JButton save_Btn;
    private javax.swing.JLabel searchBtn;
    private javax.swing.JLabel splitter1;
    private javax.swing.JLabel splitter2;
    private javax.swing.JButton viewAll_Btn;
    private javax.swing.JButton viewBB_Btn;
    private javax.swing.JButton viewHostel_Btn;
    private javax.swing.JButton viewHotel_Btn;
    // End of variables declaration//GEN-END:variables
}
